// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-t-1Fl-hbxwhzYhfDXkjwZV2jW2CAI_A',
    appId: '1:544715288062:web:ad7678a664edc8581364af',
    messagingSenderId: '544715288062',
    projectId: 'smart-disaster-management-sys',
    authDomain: 'smart-disaster-management-sys.firebaseapp.com',
    storageBucket: 'smart-disaster-management-sys.firebasestorage.app',
    measurementId: 'G-PLKFPHE13W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNwJTrPCKMrYZqsqiILVhwy6Fnv-058pk',
    appId: '1:544715288062:android:fdd893640f7e8c3f1364af',
    messagingSenderId: '544715288062',
    projectId: 'smart-disaster-management-sys',
    storageBucket: 'smart-disaster-management-sys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsoE75dgBcWwmOSPISxaboTyMc0n5g1OA',
    appId: '1:544715288062:ios:1bf4e2dad02a59bd1364af',
    messagingSenderId: '544715288062',
    projectId: 'smart-disaster-management-sys',
    storageBucket: 'smart-disaster-management-sys.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsoE75dgBcWwmOSPISxaboTyMc0n5g1OA',
    appId: '1:544715288062:ios:1bf4e2dad02a59bd1364af',
    messagingSenderId: '544715288062',
    projectId: 'smart-disaster-management-sys',
    storageBucket: 'smart-disaster-management-sys.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

}